FROM php:fpm

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Add PHP extensions
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions intl mbstring pdo_mysql zip


RUN apt-get update && \
    apt update && \
    apt install default-mysql-client -y && \
    docker-php-ext-install pdo_mysql
