# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3'

services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql


  php:
    build: docker/php
    volumes:
      # - ./Docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./:/app
    working_dir: /app

    depends_on:
      - mariadb

  nginx:
    build: docker/nginx
    volumes:
      # - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app

    depends_on:
      - php
    ports:
      - 8000:80

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1

  # dcru phpqa php-cs-fixer fix --config=".php-cs-fixer.php"
  # dcru phpqa phpstan analyse --level=max src
  phpqa:
    image: jakzal/phpqa
    working_dir: /project
    volumes:
      - .:/project

volumes:
  db-data:
